// LANGUAGE SCRIPT
language-js-src:	"js/lang/default.js"

// LANGUAGE LINKS
text-decoration-en:	"text-decoration:underline"
text-decoration-de:	"text-decoration:none"
text-decoration-it:	"text-decoration:none"
text-decoration-hr:	"text-decoration:none"

// STRINGS
house:				House
about: 				About
location: 			Location
pricing:			Pricing
contact: 			Contact

// CAROUSEL
head1: Oasis of peace
head2: Clear sea
head3: Unspoiled nature

lead1:	The islands have long been known as an oasis of peace for travelers giving them an overwhelming experience of relaxation and spiritual and physical rest.

lead2:	One of the most beautiful things about Dugi Otok are it's wonderful beaches and coves. It's crystal clear sea is inviting and the splendor of underwater life leaves you in awe.

lead3:	Unspoiled nature, rich flora and fauna, National Park Kornati and Nature Park Telašćica are unique to Dugi Otok.

// ABOUT
about-text: <span class="firstcharacter">H</span>ouse Marija is a family owned apartment house located in the small town of Brbinj on the island of Dugi Otok. With it's four apartments it is conveniently located on the tip of cove Jaz, only 20 m from the sea, and 200 m from the beach. It offers an excellent surrounding for a peaceful and relaxing vacation. Each apartment has a spacious terrace overlooking the sea, prefect for enjoying your daily meal or a glass of wine in the evening. Apartments are around 50 m<sup>2</sup> each and have two separate bedrooms and a dining room with a fully equipped kitchen. Plenty of parking space for personal vehicles is available right next to the house and there is also a possibility of setting a smaller boat to berth. Close at hand, one can find a few cozy restaurants, a small grocery store and a post office. The town is connected with Zadar by ferry operating multiple times a day.

house-bullet-title: HOUSE MARIJA
house-bullet1: 4 - 5 persons per apartment
house-bullet2: two double rooms + one additional bed
house-bullet3: dining room with kitchen and television
house-bullet4: one bathroom + one small toilet
house-bullet5: spacious terrace overlooking the sea
house-bullet6: interior around 50 m<sup>2</sup>
house-bullet7: just 20 m from the sea

// LOCATION
location-text: <span class="firstcharacter">D</span>ugi Otok (Croatian for 'Long Island') is located off the Dalmatian coast, west of ancient Zadar. It is the largest and eastern-most island of the Zadar archipelago, and derives its name from its distinctive shape (it is 45 km long by 5 km wide). It is an island of great diversity and contrast. The south-west part facing the open sea is steep and dominated by beautiful cliffs of Nature Park Telašćica. Located to the south is the National Park Kornati with it's 89 little wonders (islands). On the north-east side one can find quiet coves and beautiful beaches, the most famous of those being beach Sakarun. Nearby and surrounded by a serene pine forest is the lighthouse Veli Rat. With it's 42 m of height it is the tallest lighthouse in the Adriatic.

location-bullet-title: DUGI OTOK
location-bullet1: 45 km long by 5 km wide
location-bullet2: west of ancient Zadar
location-bullet3: nature park Telašćica
location-bullet4: national park Kornati
location-bullet5: Sakarun beach
location-bullet6: lighthouse Veli Rat

// PRICING
a4caption: 	A<sub>4</sub> (4 persons max.)
a5caption: 	A<sub>4+1</sub> (5 persons max.)
period: 	period
persons:	persons
price:		price per night
minstay:	min. nights

conditions: Listed prices cover costs of water, electricity and gas. Also included in the price are clean bed linen, clean towels and a final cleaning of the apartment. Reservations are possible with an advance payment of 25% from the total price, the remaining 75% is payed upon entry in the apartment. If there is a bank transaction fee, it is payed by the guest. Tourist tax is payed separately and it amounts to 2.5 HRK per day for persons of age 12 to 18, and 5 HRK per day for persons above 18 years of age.

tax:		tourist tax
age: 		age

// CONTACT
sime:		Šime Babac
mail: 		mail
phone: 		phone
mobile: 	mobile
fax: 		fax
enable-js:	please enable JavaScript