// language script
language-js-src:	"js/lang/default.js"

// language links
text-decoration-en:	"text-decoration:underline"
text-decoration-de:	"text-decoration:none"
text-decoration-it:	"text-decoration:none"
text-decoration-hr:	"text-decoration:none"

// strings
house:					House
about: 					About
location: 			Location
gallery:				Gallery
contact: 				Contact
language: 			Language

// carousel
head1: Oasis of peace
head2: Clear sea
head3: Unspoiled nature

lead1:	The islands have long been known as an oasis of peace for travellers giving them an overwhelming experience of relaxation and spiritual and physical rest.

lead2:	One of the most beautiful things about Dugi Otok are it's wonderful beaches and coves. It's cristal clear sea is inviting and the splendor of underwater life leaves you in awe.

lead3:	Unspoiled nature, rich flora and fauna, National Park Kornati and Nature Park Telašćica are unique to Dugi Otok.

about-text: House Marija is a familiy owned apartment house located in the small town of Brbinj on the island of Dugi Otok. With it's four apartments it is conveniently located on the tip of cove Jaz, only 20m from the sea, and 200m from the beach. It offers an excellent surrounding for a peaceful and relaxing vacation. Each apartment has a spacious terrace overlooking the sea, prefect for enjoying your daily meal or a glass of wine in the evening. Apartments are around 50m<sup>2</sup> each and have two separate bedrooms and a dining room with a fully equipped kitchen.