// LANGUAGE SCRIPT
language-js-src:	"js/lang/default.js"

// LANGUAGE LINKS
text-decoration-en:	"text-decoration:underline"
text-decoration-de:	"text-decoration:none"
text-decoration-it:	"text-decoration:none"
text-decoration-hr:	"text-decoration:none"

// STRINGS
house:				House
about: 				About
location: 			Location
contact: 			Contact

// CAROUSEL
head1: Oasis of peace
head2: Clear sea
head3: Unspoiled nature

lead1:	The islands have long been known as an oasis of peace for travellers giving them an overwhelming experience of relaxation and spiritual and physical rest.

lead2:	One of the most beautiful things about Dugi Otok are it's wonderful beaches and coves. It's cristal clear sea is inviting and the splendor of underwater life leaves you in awe.

lead3:	Unspoiled nature, rich flora and fauna, National Park Kornati and Nature Park Telašćica are unique to Dugi Otok.

// ABOUT
about-text: <span class="firstcharacter">H</span>ouse Marija is a familiy owned apartment house located in the small town of Brbinj on the island of Dugi Otok. With it's four apartments it is conveniently located on the tip of cove Jaz, only 20 m from the sea, and 200 m from the beach. It offers an excellent surrounding for a peaceful and relaxing vacation. Each apartment has a spacious terrace overlooking the sea, prefect for enjoying your daily meal or a glass of wine in the evening. Apartments are around 50 m<sup>2</sup> each and have two separate bedrooms and a dining room with a fully equipped kitchen.

house-bullet-title: HOUSE MARIJA
house-bullet1: 4-5 persons
house-bullet2: 2 double rooms with 1 additional bed available
house-bullet3: fully equipped kitchen
house-bullet4: interior around 50 m<sup>2</sup>
house-bullet5: 1 full bathroom
house-bullet6: 20 m from the sea

// LOCATION
location-text: <span class="firstcharacter">D</span>ugi Otok (Croatian for 'Long Island') is located off the Dalmatian coast, west of ancient Zadar. It is the largest and eastern-most island of the Zadar archipelago, and derives its name from its distinctive shape (it is 45 km long by 5 km wide). It is an island of great diversity and contrast. The south-west part facing the open sea is steep and dominated by beautiful cliffs of Nature Park Telašćica. Located to the south is the National Park Kornati with it's 89 little wonders (islands). On the north-east side one can find quiet coves and beautiful beaches, the most famous of those being beach Sakarun. Nearby and surrounded by a serene pine forest is the lighthouse Veli Rat. With it's 42 m of height it is the tallest lighthouse in the Adriatic sea.

location-bullet-title: DUGI OTOK
location-bullet1: west of ancient Zadar
location-bullet2: nature park Telašćica
location-bullet3: national park Kornati
location-bullet4: Sakarun beach
location-bullet5: lighthouse Veli Rat

// CONTACT
sime:		Šime Babac
mail: 		mail
phone: 		phone
mobile: 	mobile
fax: 		fax