// LANGUAGE SCRIPT
language-js-src:	"js/lang/hr.js"

// LANGUAGE LINKS
text-decoration-en:	"text-decoration:none"
text-decoration-de:	"text-decoration:none"
text-decoration-it:	"text-decoration:none"
text-decoration-hr:	"text-decoration:underline"

// STRINGS
house:				Kuća
about: 				O nama
location: 			Lokacija
pricing:			Cijene
contact: 			Kontakt

// CAROUSEL
head1: Oaza mira
head2: Čisto more
head3: Netaknuta priroda

lead1:	Otoci su od davnina poznati kao oaze mira koje putnicima pružaju doživljaj posvemašnjeg opuštanja te duhovnog i tjelesnog odmora.

lead2:	Jedno od najljepših prirodnih bogatstava Dugog Otoka zasigurno su njegove plaže i uvale. Kristalno čisto more mami svojom ljepotom, a raskoš podvodnog života izaziva divljenje.

lead3:	Netaknuta priroda, bogata flora i fauna, Nacionalni park Kornati te Park prirode Telašćica jedinstveni su za Dugi Otok.

// ABOUT
about-text: <span class="firstcharacter">K</span>uća Marija u vlasništvu obitelji Babac smještena je u malom mjestu Brbinj na Dugom Otoku. Sa svoja četiri apartmana nalazi se točno na vrhu uvale Jaz, samo 20 m od mora i 200 m od plaže. Sama kuća pruža prirodno okruženje za miran i opuštajući odmor. Svaki od apartmana ima prostranu terasu s pogledom na more, savršenu za uživanje u jelu ili pak čaši vina uvečer. Apartmani su veličine oko 50 m<sup>2</sup> i svaki ima dvije odvojene spavaće sobe, te blagovaonu s kuhinjom. Dovoljno prostora za parking osobnih vozila ima pored kuće, a postoji i mogućnost vezivanja manje brodice u uvali ispred kuće. U blizini nalazi se nekoliko lokalnih restorana, jedna manja trgovina i pošta. Samo mjesto Brbinj povezano je sa Zadrom trajektnom linijom koja prometuje nekoliko puta dnevno.

house-bullet-title: KUĆA MARIJA
house-bullet1: 4-5 osoba po apartmanu
house-bullet2: 2 dvokrevetne sobe + 1 pomoćni ležaj
house-bullet3: blagovaona s kuhinjom + tv
house-bullet4: 1 kupaona + 1 mali zahod
house-bullet5: terasa s pogledom na more
house-bullet6: veličina oko 50 m<sup>2</sup>
house-bullet7: 20 m od mora

// LOCATION
location-text: <span class="firstcharacter">D</span>ugi Otok jedan je od dalmatinskih otoka smješten zapadno od drevnog Zadra. On je najzapadniji i najveći otok u Zadarskom arhipelagu, a ime je dobio po svom specifičnom dugoljastom obliku. To je otok prepun raznolikosti i kontrasta. Na jugozapadnom dijelu otoka koji gleda prema otvorenom moru, dominiraju klifovi i prelijepe stijene parka prirode - Telašćice. Prema jugu nalazi se nacionalni park Kornati sa svojih 89 malih čuda (otočiča). Na sjeveroistočnom dijelu otoka može se pronaći mnoštvo mirnih uvala i prelijepih plaža od kojih je zasigurno najpoznatija plaža Sakarun. U neposrednoj okolici, okružen gustom borovom šumom izdiže se i svjetionik Veli Rat. Sa svojih 42 m visine, to je najviši svjetionik u Jadranskome moru...

location-bullet-title: DUGI OTOK
location-bullet1: 45 km dug i 5 km širok
location-bullet2: zapadno od starog Zadra
location-bullet3: park prirode Telašćica
location-bullet4: nacionalni park Kornati
location-bullet5: plaža Sakarun
location-bullet6: svjetionik Veli Rat

// PRICING
a4caption: 	A<sub>4</sub> (4 osobe max.)
a5caption: 	A<sub>4+1</sub> (5 osoba max.)
period: 	period
persons:	osoba
price:		cijena/noćenju
minstay:	min. noćenja

conditions: U sve navedene cijene uključeni su troškovi vode, struje i plina, čista posteljina i ručnici, te završno čišćenje apartmana. Rezervacije su moguće uz avansnu uplatu u iznosu 25% od ukupne cijene, dok se preostalih 75% plaća pri ulasku u apartman. Troškove bankovne transakcije, ako ih ima, plaća gost. Boravišna pristojba plaća se odvojeno i iznosi 2.5 HRK za osobe između 12 i 18 godina, te 5 HRK za osobe starije od 18 godina.

tax:		boravišna pristojba
age: 		dob

// CONTACT
sime:		Šime Babac
mail: 		mail
phone: 		tel
mobile: 	mob
fax: 		fax