// language script
language-js-src:	"js/lang/hr.js"

// language links
text-decoration-en:	"text-decoration:none"
text-decoration-de:	"text-decoration:none"
text-decoration-it:	"text-decoration:none"
text-decoration-hr:	"text-decoration:underline"

// gallery img titles
img1-title:	"naslov1"
img2-title:	"naslov2"
img3-title:	"naslov3"

// strings
house:					Kuća
about: 					O nama
location: 			Lokacija
gallery:				Galerija
contact: 				Kontakt
language: 			Jezik

// carousel
head1: Oaza mira
head2: Čisto more
head3: Netaknuta priroda

lead1:	Otoci su od davnina poznati kao oaze mira koje putnicima pružaju doživljaj posvemašnjeg opuštanja te duhovnog i tjelesnog odmora.
lead2:	Jedno od najljepših prirodnih bogatstava Dugog otoka zasigurno su njegove plaže i uvale. Kristalno čisto more mami svojom ljepotom, a raskoš podvodnog života izaziva divljenje. 
lead3:	Netaknuta priroda, bogata flora i fauna, Nacionalni park Kornati te Park prirode Telašćica jedinstveni su za Dugi Otok.

about-text: Kuća Marija...
