// LANGUAGE SCRIPT
language-js-src:	"js/lang/hr.js"

// LANGUAGE LINKS
text-decoration-en:	"text-decoration:none"
text-decoration-de:	"text-decoration:none"
text-decoration-it:	"text-decoration:none"
text-decoration-hr:	"text-decoration:underline"

// STRINGS
house:				Kuća
about: 				O nama
location: 			Lokacija
pricing:			Cijene
contact: 			Kontakt

// CAROUSEL
head1: Oaza mira
head2: Čisto more
head3: Netaknuta priroda

lead1:	Otoci su od davnina poznati kao oaze mira koje putnicima pružaju doživljaj posvemašnjeg opuštanja te duhovnog i tjelesnog odmora.

lead2:	Jedno od najljepših prirodnih bogatstava Dugog Otoka zasigurno su njegove plaže i uvale. Kristalno čisto more mami svojom ljepotom, a raskoš podvodnog života izaziva divljenje.

lead3:	Netaknuta priroda, bogata flora i fauna, Nacionalni park Kornati te Park prirode Telašćica jedinstveni su za Dugi Otok.

// ABOUT
about-text: <span class="firstcharacter">K</span>uća Marija u vlasništvu obitelji Babac smještena je u malom mjestu Brbinj na Dugom Otoku. Sa svoja četiri apartmana nalazi se točno na vrhu uvale Jaz, samo 20 m od mora i 200 m od plaže. Sama kuća pruža prirodno okruženje za miran i opuštajući odmor. Svaki od apartmana ima prostranu terasu s pogledom na more, savršenu za uživanje u jelu ili pak čaši vina uvečer. Apartmani su veličine oko 50 m<sup>2</sup> i svaki ima dvije odvojene spavaće sobe, te blagovaonu s kuhinjom. Dovoljno prostora za parking osobnih vozila ima pored kuće, a postoji i mogućnost vezivanja manje brodice u uvali ispred kuće. U blizini nalazi se nekoliko lokalnih restorana, jedna manja trgovina i pošta. Samo mjesto Brbinj povezano je sa Zadrom trajektnom linijom koja prometuje nekoliko puta dnevno.

house-bullet-title: KUĆA MARIJA
house-bullet1: 4-5 osoba po apartmanu
house-bullet2: 2 dvokrevetne sobe + 1 pomoćni ležaj
house-bullet3: blagovaona s kuhinjom + tv
house-bullet4: 1 kupaona + 1 mali zahod
house-bullet5: terasa s pogledom na more
house-bullet6: veličina oko 50 m<sup>2</sup>
house-bullet7: 20 m od mora

// LOCATION
location-text: <span class="firstcharacter">D</span>ugi Otok (Croatian for 'Long Island') is located off the Dalmatian coast, west of ancient Zadar. It is the largest and eastern-most island of the Zadar archipelago, and derives its name from its distinctive shape (it is 45 km long by 5 km wide). It is an island of great diversity and contrast. The south-west part facing the open sea is steep and dominated by beautiful cliffs of Nature Park Telašćica. Located to the south is the National Park Kornati with it's 89 little wonders (islands). On the north-east side one can find quiet coves and beautiful beaches, the most famous of those being beach Sakarun. Nearby and surrounded by a serene pine forest is the lighthouse Veli Rat. With it's 42 m of height it is the tallest lighthouse in the Adriatic.

location-bullet-title: DUGI OTOK
location-bullet1: 45 km dug i 5 km širok
location-bullet2: zapadno od starog Zadra
location-bullet3: park prirode Telašćica
location-bullet4: nacionalni park Kornati
location-bullet5: plaža Sakarun
location-bullet6: svjetionik Veli Rat

// PRICING
a4caption: 	A<sub>4</sub> (4 osobe max.)
a5caption: 	A<sub>4+1</sub> (5 osoba max.)
period: 	period
persons:	osoba
price:		cijena/noći
minstay:	min. noći

conditions: Listed prices cover costs of water, electricity and gas. Also included in the price are clean bed linen, clean towels and a final cleaning of the apartment. Reservations are possible with an advance payment of 25% from the total price, the remaining 75% is payed upon entry in the apartment. If there is a bank transaction fee, it is payed by the guest. Tourist tax is payed separately and it amounts to 2.5 HRK per day for persons of age 12 to 18, and 5 HRK per day for persons above 18 years of age.

tax:		boravišna pristojba
age: 		dob

// CONTACT
sime:		Šime Babac
mail: 		mail
phone: 		tel
mobile: 	mob
fax: 		fax